name: theta
description: RICOH THETA WebAPI package for Dart
version: 0.1.0
author: Oppkey
homepage: https://codetricity.github.io/theta

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.4
  effective_dart: ^1.3.2
